### ISSUE TITLE
Replace Google-Captcha with Django-Captcha.

### ISSUE THREAD

**Issue by souravbadami** [OWASP/BLT#683] opened 2021-03-04 17:47 UTC

**Comment by souravbadami** [comment] 2021-03-04 17:48
@ankit2001 - Would you like to work on this?

**Comment by fredfalcon** [comment] 2021-03-04 18:08
Duplicate of #681

**Closed by fredfalcon** 2021-03-04 18:08 UTC
Labels: loc: fullstack, priority: medium, type: enhancement

**Comment by ankit2001** [comment] 2021-03-04 20:51
Yeah sure.

**Comment by ankit2001** [comment] 2021-03-04 20:53
I will definately going to fix this in a day @souravbadami .
