### ISSUE TITLE
Task: Uploading image, then getting URL back from the backend and then using that in markdown for description.

### ISSUE THREAD

**Issue by kr-2003** [OWASP/BLT#1675] opened 2024-01-16 18:19 UTC
**Is your feature request related to a problem? Please describe.**
A new feature that allows users to upload an image, receive the associated URL from the backend, and seamlessly integrate this URL within Markdown for image descriptions. This enhancement provides users with a more dynamic and versatile approach to incorporating images into their content, moving beyond the conventional method of directly pasting image URLs. 

**Describe the solution you'd like**
Most of the solutions have been discussed in https://github.com/OWASP/BLT/issues/1206. I would like to further discuss upon it.
Furthermore, when the user selects "Add Image" in the description, they will be presented with the option to either upload an image from their computer or paste a URL.

**Comment by kr-2003** [comment] 2024-01-16 18:19
@DonnieBLT I would like to discuss upon this enhancement.

**Comment by DonnieBLT** [comment] 2024-01-27 19:41
Duplicate of #1206

**Closed by DonnieBLT** 2024-01-27 19:41 UTC
Labels: enhancement, task
