### ISSUE TITLE
Add a python linter.

### ISSUE THREAD

**Issue by souravbadami** [OWASP/BLT#285] opened 2017-06-11 19:19 UTC

**Comment by btotharye** [comment] 2017-10-04 17:54
anything particular you are looking for this or just a linter for travis?

**Comment by seanauriti** [comment] 2017-10-04 17:57
For Travis is fine

**Comment by btotharye** [comment] 2017-10-04 18:03
ok if you want to assign to me I'll work on it today after work unless someone else already is working this

**Comment by goyal-sidd** [comment] 2017-10-18 19:34
@btotharye assigned to you.

**Comment by souravbadami** [comment] 2018-02-17 11:46
Hi @btotharye -- Any updates on this ?

**Comment by fredfalcon** [comment] 2021-03-29 16:41
Duplicate of #417

**Closed** 2021-03-29 16:41 UTC
Labels: help wanted, loc: backend, priority: high, type: enhancement
