### ISSUE TITLE
User not able to login

### ISSUE THREAD

**Issue by farziengineer** [OWASP/BLT#209] opened 2017-06-06 13:56 UTC
User is taken to signup page after login option from modals is selected .

**Comment by souravbadami** [comment] 2017-06-06 14:00
Hi @farziengineer -- Could you please tell us the steps to reproduce this issue ?

**Comment by farziengineer** [comment] 2017-06-06 14:03
Logout. Then try to login. I have tried it with fb and gmail. It says to enter username and the email id. If you do so you are presented with error that user is already registered.

**Comment by souravbadami** [comment] 2017-06-06 14:05
If I'm correct, this has nothing to do with the modal implementation. It just gave another view to log into the system away from navbar. Also, I just checked in and it is working fine for me. Let's see if others are facing this issue.

**Comment by farziengineer** [comment] 2017-06-06 14:08
Yes it has nothing to do with modal implementation. I'll try and tell you.

**Comment by Roboneet** [comment] 2017-06-06 14:23
@farziengineer , I think you got the error because your fb account , gmail account and original bugheist account uses the same email address.  When I tried with a different gmail account , it was successful. Correct me if I'm wrong

**Comment by farziengineer** [comment] 2017-06-06 14:29
Yes correct :+1:

**Comment by seanauriti** [comment] 2017-06-07 21:24
I think this is not an issue, I believe Allauth links the accounts?  Are you able to login with both accounts now @farziengineer ?

**Closed by seanauriti** 2017-06-07 21:24 UTC
Labels: triage

**Comment by farziengineer** [comment] 2017-06-07 21:30
Yes @seanauriti  I was didnt notice.
